# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Event',
        ),
    ]
